version: '3'
services:




  src:
    build: ./src
    ports:
      - "8081:8081"
    volumes:
      - ./src:/var/www/html
    labels:
      - "traefik.http.routers.api.rule=(Host(`app.localhost`) && PathPrefix(`/src`))"
    depends_on:
      - traefik
      - mysql



  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: desurance
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql



  onchain-backend:
    build: ./onchain-backend
    ports:
      - "8085:8085"
    labels:
      - "traefik.http.routers.onchain-backend.rule=(Host(`app.localhost`) && PathPrefix(`/onchain-backend`))"
    depends_on:
      - traefik
  

  
  cmc-proxy:
    build: ./cmc-proxy
    ports:
      - "8082:8082"
    labels:
      - "traefik.http.routers.cmc-proxy.rule=(Host(`app.localhost`) && PathPrefix(`/cmc-proxy`))"
    depends_on:
      - traefik



  traefik:
    image: traefik:v2.9
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8084:8084"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dynamic_conf:/etc/traefik/dynamic
