version: '3'
services:

  website:
    build: ./website
    ports:
      - "8081:8081"
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.website.rule=Host(`desurance.localhost`)"



  mysql:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: desurance
      MYSQL_USER: razor
      MYSQL_PASSWORD: secret
      TZ: Europe/Berlin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8089:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)"


  cmc-proxy:
    build: ./cmc-proxy
    ports:
      - "8082:8082"
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.cmc-proxy.rule=Host(`proxy.localhost`)"


  traefik:
    image: traefik:v2.9
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
